export const site = {
  name: "Ammari Dental",
  legalName: "Ammari Dental",
  doctor: "Dr. Raed Ammari",
  url: "https://www.auroragentledentist.com",
  phone: "(303) 283-8009",
  phoneTel: "+13032838009",
  fax: "(303) 337-7809",
  emergencyPhone: "720-443-8178",
  emergencyTel: "+17204438178",
  email: "info@auroragentledentist.com",
  address: {
    street: "1344 S Chambers Road, Suite 203",
    city: "Aurora",
    state: "CO",
    zip: "80017",
    country: "US",
  },
  geo: { lat: 39.6792, lng: -104.7521 },
  hours: [
    { day: "Monday", open: "08:30", close: "17:00" },
    { day: "Tuesday", open: "08:30", close: "17:00" },
    { day: "Wednesday", open: "08:30", close: "17:00" },
    { day: "Thursday", open: "08:30", close: "17:00" },
    { day: "Friday", open: "10:00", close: "15:00", note: "(one Friday per month closed)" },
    { day: "Saturday", closed: true },
    { day: "Sunday", closed: true },
  ],
  // Consumed individually for map links, and in full by the LocalBusiness
  // `sameAs`. Placeholder entries (bare facebook.com / yelp.com / linkedin.com
  // homepages) were removed — asserting those as the practice's own profiles
  // is an entity-resolution error. Add real profile URLs here when they exist.
  social: {
    google: "https://maps.google.com/?q=1344+S+Chambers+Road+Suite+203+Aurora+CO+80017",
  },
  staff: [
    {
      name: "Dr. Raed Ammari, DDS",
      role: "Founding Dentist",
      bio: "Dr. Ammari has practiced gentle family and cosmetic dentistry in Aurora since 2003. He focuses on conservative, comfortable care and treats every patient like a member of his family.",
      image: "/images/staff/dr-ammari.jpg",
    },
    {
      name: "",
      role: "Associate Dentist",
      bio: "Our associate dentist brings warmth and modern technique to general and cosmetic dentistry, with thorough explanations and a steady hand.",
      image: "/images/staff/placeholder.svg",
    },
    {
      name: "",
      role: "Office Manager",
      bio: "Our office manager keeps things running smoothly — from insurance questions to scheduling and treatment coordination.",
      image: "/images/staff/placeholder.svg",
    },
    {
      name: "",
      role: "Administrative Assistant",
      bio: "Often the first friendly voice you'll hear, helping with check-in, paperwork, and getting your visit started right.",
      image: "/images/staff/placeholder.svg",
    },
  ],
  insurances: [
    { name: "Aetna",                       slug: "aetna",            logo: "/images/insurance/aetna.svg" },
    { name: "Ameritas",                    slug: "ameritas",         logo: "/images/insurance/ameritas.svg" },
    { name: "Anthem Blue Cross Blue Shield", slug: "anthem",         logo: "/images/insurance/anthem.svg" },
    { name: "Assurant",                    slug: "assurant",         logo: "/images/insurance/assurant.svg" },
    { name: "Careington",                  slug: "careington",       logo: "/images/insurance/careington.svg" },
    { name: "CHP+",                        slug: "chpplus",          logo: "/images/insurance/chpplus.svg" },
    { name: "Cigna",                       slug: "cigna",            logo: "/images/insurance/cigna.png" },
    { name: "Delta Dental",                slug: "delta-dental",     logo: "/images/insurance/delta-dental.svg" },
    { name: "DenteMax",                    slug: "dentemax",         logo: "/images/insurance/dentemax.svg" },
    { name: "GEHA",                        slug: "geha",             logo: "/images/insurance/geha.png" },
    { name: "Guardian",                    slug: "guardian",         logo: "/images/insurance/guardian.svg" },
    { name: "Humana",                      slug: "humana",           logo: "/images/insurance/humana.svg" },
    { name: "Liberty Dental",              slug: "liberty-dental",   logo: "/images/insurance/liberty-dental.svg" },
    { name: "Lincoln Financial",           slug: "lincoln",          logo: "/images/insurance/lincoln.svg" },
    { name: "Medicaid (Dentaquest)",       slug: "dentaquest",       logo: "/images/insurance/dentaquest.svg" },
    { name: "MetLife",                     slug: "metlife",          logo: "/images/insurance/metlife.svg" },
    { name: "Principal",                   slug: "principal",        logo: "/images/insurance/principal.svg" },
    { name: "Sun Life",                    slug: "sunlife",          logo: "/images/insurance/sunlife.svg" },
    { name: "United Concordia",            slug: "united-concordia", logo: "/images/insurance/united-concordia.png" },
    { name: "United Healthcare",           slug: "united-healthcare",logo: "/images/insurance/united-healthcare.svg" },
  ],
};
