export const site = {
  name: "Ammari Dental",
  legalName: "Ammari Dental",
  doctor: "Dr. Raed Ammari",
  url: "https://www.auroragentledentist.com",
  phone: "(303) 283-8009",
  phoneTel: "+13032838009",
  fax: "(303) 337-7809",
  emergencyPhone: "720-443-8178",
  emergencyTel: "+17204438178",
  email: "info@auroragentledentist.com",
  address: {
    street: "1344 S Chambers Road, Suite 203",
    city: "Aurora",
    state: "CO",
    zip: "80017",
    country: "US",
  },
  geo: { lat: 39.6792, lng: -104.7521 },
  hours: [
    { day: "Monday", open: "08:30", close: "17:00" },
    { day: "Tuesday", open: "08:30", close: "17:00" },
    { day: "Wednesday", open: "08:30", close: "17:00" },
    { day: "Thursday", open: "08:30", close: "17:00" },
    { day: "Friday", open: "10:00", close: "15:00", note: "(one Friday per month closed)" },
    { day: "Saturday", closed: true },
    { day: "Sunday", closed: true },
  ],
  social: {
    facebook: "https://www.facebook.com/",
    yelp: "https://www.yelp.com/",
    google: "https://maps.google.com/?q=1344+S+Chambers+Road+Suite+203+Aurora+CO+80017",
    linkedin: "https://www.linkedin.com/",
  },
  staff: [
    {
      name: "Dr. Raed Ammari, DDS",
      role: "Founding Dentist",
      bio: "Dr. Ammari has practiced gentle family and cosmetic dentistry in Aurora since 2003. He focuses on conservative, comfortable care and treats every patient like a member of his family.",
      image: "/images/staff/dr-ammari.jpg",
    },
    {
      name: "",
      role: "Associate Dentist",
      bio: "Our associate dentist brings warmth and modern technique to general and cosmetic dentistry, with thorough explanations and a steady hand.",
      image: "/images/staff/placeholder.svg",
    },
    {
      name: "",
      role: "Office Manager",
      bio: "Our office manager keeps things running smoothly — from insurance questions to scheduling and treatment coordination.",
      image: "/images/staff/placeholder.svg",
    },
    {
      name: "",
      role: "Administrative Assistant",
      bio: "Often the first friendly voice you'll hear, helping with check-in, paperwork, and getting your visit started right.",
      image: "/images/staff/placeholder.svg",
    },
  ],
  insurances: [
    "Aetna",
    "Ameritas",
    "Anthem Blue Cross Blue Shield",
    "Assurant",
    "Careington",
    "CHP+",
    "Cigna",
    "Delta Dental",
    "Dentemax",
    "GEHA",
    "Guardian",
    "Humana",
    "Liberty Dental",
    "Lincoln Financial",
    "Medicaid (Dentaquest)",
    "MetLife",
    "Principal",
    "Sun Life",
    "United Concordia",
    "United Healthcare",
  ],
};
